Header
MariWieg/practicFigma pull request #1
Opened 2024-08-16 19:03 UTC by MariWieg

2024-09-06 11:33 UTC, romankrivopalov approved these changes

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +                    <ul class="header__list">
появился класс header__list, по БЭМ это элемент, но элемент иожет находиться только в блоке, а класса header нет

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +                <div class="blue__container-img container-img">
тут путаница с классами, это не прям ошибка, но можно лучше

у тебя есть блок blue__container, а blue__container-img выглядит как модифткатор, его бы либо переименовать в blue__image (или такие элементы ещё можно cover называть), или сделать модификатор, те blue__container_img (blue__container_cover)

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +                    <a class="logo" href="https://www.google.com"/>DIA</a>
тк это петпроект, лучше просто поставь заглушку href='#', чтобы те кто щашёл посмотреть итоговый результат при нажатии не ушли с сайта

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +                    <p class="hireUs">Hire us</p>
не понятное название класса

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +                    <div class="container__title">Global digital agency</div>
а почему не h1 ?

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +                    <div class="container__button"><button class="button">Learn more</button></div>
лишняя обёртка в виде div, просто оставь button, а если потребуется например его позиционирование заведи для класса button модификатор

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
>          <div class="blue">
а вообще выглядит как лишняя обёртка, можно просто убрать

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +                    <div class="container-img__social">Facebook Twitter Instagram</div>
тут скорее подойдёт список (ul) внутри которого должны быть ссылки на соц сети

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +                        <img src="/assets/images/first_img.jpg" class="imgHeader">
снова странный нейминг класса, и нужно по всему коду подобные переделать :)

2024-09-06 11:33 UTC, romankrivopalov commented on styles/style.scss
> +.blue {
не критично, но ставь правильные отступы, те после import пустая строка, а внутри blue (4я строка убери отступ)

2024-09-06 11:33 UTC, romankrivopalov commented on styles/style.scss
> +
вот такие отступы тоже не нужны

2024-09-06 11:33 UTC, romankrivopalov commented on styles/style.scss
> +        flex-direction: row;
flex-direction по умолчанию row, писать не обязательно

2024-09-06 11:33 UTC, romankrivopalov commented on styles/style.scss
> +    text-decoration: none;
старайся указывать сначала все свойства отвечающие за позиционирование, затем размеры и потом визуал

2024-09-06 11:33 UTC, romankrivopalov commented on styles/style.scss
> +        color: rgb(255, 255, 255);
цвет нужно указывать в hex

2024-09-06 11:33 UTC, romankrivopalov commented on styles/style.scss
> +    gap: 0px;
это наверное стоит убрать)

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +                    <p class="hireUs">Hire us</p>
не ошибка, но тут можно сделать как элемент списка, только со свои модификатором чтобы задать отступ

2024-09-06 11:33 UTC, romankrivopalov commented on index.html
> +            <div class="blue__body" >
выглядит как лишняя обёртка, тк классы от него можно перенести в родителя (тем более у него их нет)

2024-09-06 11:36 UTC, romankrivopalov requested changes

2024-09-06 11:36 UTC, romankrivopalov commented on index.html
>          <div class="blue">
так блоки лучше не называть, тк его имя не отображает содержимое, больше подойдёт cover или header (в засимости как ты решишь использовать navbar, те navbar может быть header)

а вообще выглядит как лишняя обёртка, можно просто убрать

2024-09-06 11:40 UTC, romankrivopalov approved these changes

2024-09-06 11:40 UTC, romankrivopalov commented on index.html
>          <div class="blue">
так блоки лучше не называть, тк его имя не отображает содержимое, больше подойдёт cover или header (в засимости как ты решишь использовать navbar, те navbar может быть header)

а вообще выглядит как лишняя обёртка, можно просто убрать

2024-09-06 15:47 UTC, MariWieg commented on index.html
>          <div class="blue">
fix

2024-09-06 16:58 UTC, MariWieg commented on styles/style.scss
> +    gap: 0px;
fixed

2024-09-06 16:58 UTC, MariWieg commented on styles/style.scss
> +        flex-direction: row;
fixed

2024-09-06 17:17 UTC, MariWieg commented on index.html
> +                <div class="blue__container-img container-img">
fixed

2024-09-06 17:22 UTC, MariWieg commented on index.html
> +                    <div class="container__title">Global digital agency</div>
fixed

2024-09-06 17:22 UTC, MariWieg commented on index.html
> +                    <div class="container__button"><button class="button">Learn more</button></div>
fixed

2024-09-06 17:23 UTC, MariWieg commented on index.html
> +                        <img src="/assets/images/first_img.jpg" class="imgHeader">
fixed

2024-09-06 17:23 UTC, MariWieg commented on styles/style.scss
> +.blue {
fixed

2024-09-06 17:24 UTC, MariWieg commented on styles/style.scss
> +
fixed

2024-09-06 17:24 UTC, MariWieg commented on index.html
> +            <div class="blue__body" >
fixed

2024-09-12 14:31 UTC, MariWieg commented on index.html
> +                    <a class="logo" href="https://www.google.com"/>DIA</a>
fixed

2024-09-12 14:37 UTC, MariWieg commented on index.html
> +                    <p class="hireUs">Hire us</p>
fixed ?

2024-09-16 10:56 UTC, romankrivopalov approved these changes

2024-09-16 10:56 UTC, romankrivopalov commented on index.html
> +                    <h5 class="slider__text-title">INtro<h5>
тег h5 не закрыт

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +        border-bottom-left-radius: 50%;
для button_prev и button_next лучше указать комбинированное свойство border-radius: top-left, tor-right, bottom-right, bottom-left

так же сейчас эти кнопки имеют неверное округление, тк используется значение в %, лучше указать в px (мы знаем высоту кнопки, и половина её будет значением скругления)

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +    }
это можно перенести в блок &__button_prev

```
&__button_prev {
    &::before {
    
    }
}
```

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +        content: "⟩";
тут лучше переделать
```
content: "";
display: block;
width: 20px;
height: 20px;
border-left: 2px solid #FFF;
border-bottom: 2px solid #FFF;
transform: rotate(45deg);
```

а родителю, те slider__button задать
```
display: flex;
justify-content: center;
align-items: center;
```

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +        float: left;
это описал ниже, что лучше убрать и для &__buttons задать
`display: flex;`

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +        font-size: 26px;
это лишнее

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +.hire-us{
это наверное больше является header__item, те перенеси в html его в ul, а затем создай модификатор для него, например header__item_pos_right  у которого останется только добавить оступ слева

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +
пробел)

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +    }
абсолютно правильно выделила это, тк это мы будем переиспользовать, но!)

1. зачем разделять на text и title ?
2. поскольку это заголовок, и если нам он понадобится за пределами section, мы не сможем его использовать, поэтому давай сделаем самостоятельный блок title, у которого буде псевдоэлемент before

<img width="878" alt="Снимок экрана 2024-09-16 в 13 36 12" src="https://github.com/user-attachments/assets/892e161b-9b4e-4c76-aac3-c2b78cc196f5">

2024-09-16 10:56 UTC, romankrivopalov commented on index.html
> +    <section class="section">
тут лучше использовать класс container (который и занимается уже позиционированием) а рядом указать например название блока, его можно так и назвать welcome и ему здать padding-top

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +    }
одинаковые стили в 3 классах - [DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself) :blush:
сделай 1 класс его и присвой всем 3м элементам, и убери float: left

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +        grid-template-columns: 33% 33% 33%;
тк ширина у элементов есть, просто задай displey: flex и gap

2024-09-16 10:56 UTC, romankrivopalov commented on styles/style.scss
> +    &__maintitle {
тк по рекомендациям выше, *-title должно освободиться, то лучше использовать его

2024-09-16 10:56 UTC, romankrivopalov commented on index.html
> +        <h2 class="section__maintitle">What we do</h2>
по смысловой нагрузке я бы поменял местами h2 и h3

2024-09-16 10:56 UTC, romankrivopalov commented on index.html
> +                <img src="/assets/images/1.jpg" alt="" class="section__imgCirc">
alt луше всегда заполнять, тут ситуация такая, если не понятно, что писать в него (а в alt соит описывать что изображено например - "ноутбук лежит на деревянном столе"), стоит подумать а может это не "контентное" изображение, а "декоративно" ? и если так его лучше указать через background-image

2024-09-16 10:56 UTC, romankrivopalov commented on index.html
> +                <li class="header__social-item">Facebook</li>
тут внутрь li стоит положить ссылку

2024-09-16 19:08 UTC, MariWieg commented on index.html
> +                    <h5 class="slider__text-title">INtro<h5>
fixed

2024-09-16 19:08 UTC, MariWieg commented on styles/style.scss
> +        border-bottom-left-radius: 50%;
fixed

2024-09-16 19:08 UTC, MariWieg commented on styles/style.scss
> +    }
fixed

2024-09-16 19:09 UTC, MariWieg commented on styles/style.scss
> +        content: "⟩";
fixed

2024-09-16 19:10 UTC, MariWieg commented on styles/style.scss
> +        font-size: 26px;
fixed

2024-09-16 19:14 UTC, MariWieg commented on styles/style.scss
> +.hire-us{
fixed

2024-09-16 19:16 UTC, MariWieg commented on styles/style.scss
> +
fixed

2024-09-17 01:37 UTC, MariWieg commented on styles/style.scss
> +    }
fixed

2024-09-17 01:37 UTC, MariWieg commented on styles/style.scss
> +        grid-template-columns: 33% 33% 33%;
fixed

2024-09-17 01:38 UTC, MariWieg commented on index.html
> +                <img src="/assets/images/1.jpg" alt="" class="section__imgCirc">
fixed

2024-09-17 01:39 UTC, MariWieg commented on index.html
> +                <li class="header__social-item">Facebook</li>
fixed

2024-09-20 17:26 UTC, romankrivopalov approved these changes

2024-09-20 17:26 UTC, romankrivopalov commented on index.html
> +                    <h3 class="section-title">
тут давай поменяем, я писал выше и закрыл тред тк там поменяли структуру. Всё таки этот заголовок больше похож на h2

2024-09-20 17:26 UTC, romankrivopalov commented on styles/normalize.css
> +h1 {
мы сейчас по проекту используем разные заголовки и у них есть отступы которые добавляет браузер, они нам не нужны и их лучше обнулить, чтобы не делать это для селекторов классов, давай укажем это тут: 
`h1, h2, h3, h4, h5 {
    margin: 0;
    padding: 0;
}`

но обрати внимание, что ты везде задавала отсутпы с учетом браузерных стилей, поэтому нужно везде пройти и ещё раз поправить

и ещё тут нужно указать правило для параграфа, те для тега p (также обнулить маржин и паддинг)

2024-09-20 17:26 UTC, romankrivopalov commented on styles/normalize.css
> +  font-size: 2em;
это можно убрать, размером шрифта как раз мы будем сами управлять

2024-09-20 17:26 UTC, romankrivopalov commented on styles/style.scss
> +
пробел :smiley:

2024-09-20 17:26 UTC, romankrivopalov commented on styles/style.scss
> +        max-width: 176px;
эти два свойства лучше убрать (марджин и ширину), тк если допустим что тут добавится какой нибудь элемент придётся костылять. Лучше для step__wrapper задать padding

2024-09-20 17:26 UTC, romankrivopalov commented on styles/style.scss
> +    &_numbers {
тут ошибка, ты используешь только модификатор (а точнее два модификатора), те без блока или элемента. Поэтому правильнее сделать &__numbers (те элемент), и тогда &_blue, &_yellow и тд будут применены к элементу

идея модификатора, что прописывается класс блока или элемента и он (модификатор) меняет или дополняет класс (блока или элемента)

2024-09-20 17:26 UTC, romankrivopalov commented on styles/style.scss
> +    &__list {
тут нужно дополнительно обнулить паддинги и марджины. Они постоянно добавляются для ul браузером, чтобы дать место для списков (которые мы отменили на 315й строке)

2024-09-20 17:26 UTC, romankrivopalov commented on index.html
> +    <section class="what-we-do">
тут нужно поменять, сейчас у тебя секция отталкивается марджинами, их нужно убрать (в тч этот класс является блоком а у него не должно быть внешнего позиционирования) и добавить обёртку container

а если понадобится делать вертикальные отступы лучше испольщовать padding

2024-09-20 17:26 UTC, romankrivopalov commented on index.html
> +    <section class="welcome">
почти такая же ситуация как и с what-we-do, но тут есть контейнер который не используется. Нужно обнулить все классы welcome и наверное добавить паддинг

Про паддинг важное замечание, старайся задавать везде однотипно, те если везде ипользуешь padding-top то старайся везде применять его, чтобы отталкивать элементы друг от друга

2024-09-20 17:26 UTC, romankrivopalov commented on assets/fonts/muli.css
> +    font-weight: normal;
тут я ошибся, значения для font-weight надо задать как 400 для normal и 900 для black
далее по тексту нужно пройтись и отпеределить, основное начертание и задать его для body и переопределять там где это требуется

2024-09-20 17:26 UTC, romankrivopalov commented on styles/style.scss
> +$color-white: #fff;
тут создай файл variables.scss и вынеси переменные в него как мы делали

здесь в файле нужно указать @import './variables';

2024-09-20 17:53 UTC, MariWieg commented on index.html
> +                    <h3 class="section-title">
fixed

2024-09-20 18:11 UTC, MariWieg commented on styles/normalize.css
> +h1 {
fixed

2024-09-20 18:15 UTC, MariWieg commented on styles/normalize.css
> +  font-size: 2em;
fixed

2024-09-20 18:16 UTC, MariWieg commented on styles/style.scss
> +
fixed

2024-09-20 18:32 UTC, MariWieg commented on styles/style.scss
> +        max-width: 176px;
fixed

2024-09-20 18:35 UTC, MariWieg commented on styles/style.scss
> +    &_numbers {
fixed

2024-09-20 18:37 UTC, MariWieg commented on styles/style.scss
> +    &__list {
fixed

2024-09-20 22:09 UTC, MariWieg commented on index.html
> +    <section class="what-we-do">
Не поняла это

2024-09-20 22:26 UTC, MariWieg commented on index.html
> +    <section class="welcome">
fixed and previous too....I got it

2024-09-20 22:28 UTC, MariWieg commented on index.html
> +    <section class="what-we-do">
already I got it

2024-09-20 22:43 UTC, MariWieg commented on assets/fonts/muli.css
> +    font-weight: normal;
fixed

2024-09-20 23:08 UTC, MariWieg commented on styles/style.scss
> +$color-white: #fff;
fixesd

2024-10-03 15:31 UTC, romankrivopalov approved these changes

2024-10-03 15:31 UTC, romankrivopalov commented on index.html
> +        <div class="container container_wwd">
тут не совсем ошибка, но можно не использовать модификатор, а отступ задать для welcome__maintitle (он элемент, за пределами блока использоваться он не будет и ему внешнее позиционирование задать можно)

2024-10-03 15:31 UTC, romankrivopalov commented on index.html
> +    <section class="what-we-do">
блок называется what-we-do, а все элементы внутри относятся к welcome ?

2024-10-03 15:31 UTC, romankrivopalov commented on index.html
> +                    <img src="/assets/images/1.jpg" alt="room" class="welcome__imgCirc">
что за странный нейминг класса ?)

2024-10-03 15:31 UTC, romankrivopalov commented on index.html
> +            <h3 class="welcome__maintitle">
можно переименовать просто в welcome__title

2024-10-03 15:31 UTC, romankrivopalov commented on index.html
> +                        the sable cloud beneath was dished out, and the car seemed to float in the middle of an immense dark sphere, whose upper half was strewn with silver.
весь длинный текст стоит прогнать через https://www.artlebedev.ru/typograf/

2024-10-03 15:31 UTC, romankrivopalov commented on styles/style.scss
> +    }
давай начнём задавать интерактивность, чтобы пользователю было легче понять, что с элементом можно взаимодействовать, добавь `cursor: pointer`

2024-10-03 15:31 UTC, romankrivopalov commented on styles/style.scss
> +    }
а так же можно дополнительно стилизовать при наведении, например внутри &__button можно задать примерно следующее:
```
&::hover {
    opacity: .8;
}
```
это псевдокласс который сработает, когда браузер определит, что на элемент навели курсор мыши, тут можно на своё усмотрение стилизовать любым образом

2024-10-03 15:31 UTC, romankrivopalov commented on styles/style.scss
> +        list-style-type: none;
тут также желательно задать интерактивность, те `cursor: pointer;` и добавить стили для hover

2024-10-03 15:31 UTC, romankrivopalov commented on styles/style.scss
> +
пробел)

2024-10-03 15:31 UTC, romankrivopalov commented on styles/style.scss
> +        }
по макету, у каждой цифры, есть ещё декоративный элемент, который тоже жедательно сделать через псевдоэлемент. Те можно сам псевдоэлемент вынести в &__numbers и описать его для всех один раз, а в каждом модификаторе указать отлчительные черты

2024-10-03 23:47 UTC, MariWieg commented on index.html
> +                        the sable cloud beneath was dished out, and the car seemed to float in the middle of an immense dark sphere, whose upper half was strewn with silver.
fixed

2024-10-04 17:34 UTC, MariWieg commented on index.html
> +                    <img src="/assets/images/1.jpg" alt="room" class="welcome__imgCirc">
fixed

2024-10-04 17:35 UTC, MariWieg commented on index.html
> +            <h3 class="welcome__maintitle">
fixed

2024-10-04 17:40 UTC, MariWieg commented on index.html
> +        <div class="container container_wwd">
fixed

2024-10-04 17:44 UTC, MariWieg commented on index.html
> +    <section class="what-we-do">
fixed

2024-10-04 18:05 UTC, MariWieg commented on styles/style.scss
> +    }
fixed

2024-10-04 18:19 UTC, MariWieg commented on styles/style.scss
> +        list-style-type: none;
fixed

2024-10-04 18:20 UTC, MariWieg commented on styles/style.scss
> +
fixed

2024-10-04 18:56 UTC, MariWieg commented on styles/style.scss
> +        }
fixed

2024-10-04 19:03 UTC, merged